name: metinhas
description: "Aplicativo de metas."
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: '>=3.3.2 <4.0.0'
  flutter: '3.22.2'

dependencies:
  ### Dependências padrões do Flutter
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

  ### Dependências do projeto - pub.dev

  #Utilizada na montagem dos valores na tela de Listagem de vendas/negociações
  collection: ^1.18.0
  #Informações do dispositivo
  device_info_plus: ^10.0.1
  #Para descriptografar os dados recebidos no Link na leitura do QR Code
  encrypt: ^5.0.3
  #Utilizado no campo de busca de clientes
  flutter_typeahead: ^5.2.0
  #Identificador do dispositivo
  flutter_udid: ^3.0.0
  flutter_mobx: ^2.2.1+1
  mobx: ^2.3.3+1
  flutter_modular: ^6.3.2
  #Requisições HTTP
  http: ^1.2.1
  #Internacionalização e localização
  intl: ^0.19.0
  #Manipulação de datas
  jiffy: ^6.3.0
  #Utilizado para exibição de toasts
  oktoast: ^3.4.0
  #Utilizado para busca/formatação de caminhos no sistema
  path: ^1.9.0
  #Utilizado para buscar o caminho do banco de dados
  path_provider: ^2.1.3
  #Banco de dados SQLite
  sqflite: ^2.3.3+1
  #Lib adicional do banco de dados SQLite para usara versão atualizada do SQlite
  sqflite_common_ffi: ^2.3.3
  #Dlls/Bibliotecas do SQlite atualizadas (0.5.20 = Sqlite 3.45.3+1)
  sqlite3_flutter_libs: 0.5.21
  #Para fazer o lock do banco de dados na abertura
  synchronized: ^3.1.0+1
  #Para gerar Uuid (GUIDS)
  uuid: ^4.3.3
  #Para gerenciar o numero da versão do app
  package_info_plus: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  mobx_codegen: ^2.0.5+2
  build_runner: 2.4.6

  #Para gerar os ícones do app. --//--//-- Comando para gerar os ícones: flutter pub run flutter_launcher_icons
  flutter_launcher_icons: ^0.13.1

dependency_overrides:
  intl: ^0.19.0

flutter_icons:
  min_sdk_android: 21
  android: true
  ios: true
  image_path_ios: "assets/icons/ic_launcher_ios.png"
  image_path_android: "assets/icons/ic_launcher_android.png"
  adaptive_icon_foreground: "assets/icons/ic_launcher_foreground.png"
  adaptive_icon_background: "assets/icons/ic_launcher_background.png"
  remove_alpha_ios: true
  image_path: "assets/icons/ic_launcher_ios.png"
  windows:
    generate: true
    image_path: "assets/icons/launcher.png"
    icon_size: 128

flutter:
  uses-material-design: true
